### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svZeroDSolver-Archived#11]
- delete unused blocks
- delete commented code
- simplify where possible

**Comment by mrp089** [comment]
@JonathanPham are there more blocks we can delete for now? E.g. unused, untested, under development?

**Comment by JonathanPham** [comment]
@mrp089 I think there are some other blocks we can delete. I'll take a look and make the updates.

**Comment by JonathanPham** [comment]
In pull request #13: deleted the following blocks, which are currently not in use:

- PressureSource
- IdealDiode2
- ChamberModel
- TimeDependentCapacitance
- UnsteadyRCRBlock
- RCRBlock
- PressureRef
- UnsteadyResistance

Also removed some extraneous comments and unused/untested functions.
