### ISSUE TITLE
Non-periodic coronary BCs

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svZeroDSolver-Archived#43]
Not sure where to where post this issue, so I'll post it here.

@mrp089 I just noticed that the coronary boundary conditions in the 0d text input files that you sent me in a previous [comment](https://github.com/SimVascular/svZeroDSolver/issues/14#issuecomment-876004359) are not periodic. I think this might be an issue, because in the 0d solver, we always assume that pulsatile boundary conditions are periodic (meaning that the endpoints of the time series are the same).

_Originally posted by @JonathanPham in https://github.com/SimVascular/svZeroDSolver/issues/14#issuecomment-885953553_

**Comment by mrp089** [comment]
@JonathanPham I understand it doesn't make sense to have non-periodic pressures in coronary BCs. Is this a "hard" requirement, i.e., can we not solve a `0D` problem with non-periodic BCs? Or is something that doesn't make sense, but isn't too big of an issue in cases the discrepancy between last and first time step is small?

**Comment by JonathanPham** [comment]
@mrp089 It's not a hard requirement to have periodic BCs. As long as the 0D is performing well against the 3D and 1D results (all using the same non-periodic coronary BCs), it is probably isn't a big issue.
