### ISSUE TITLE
Change coronary BC's distal pressure from "Pv" to "P_v" to match SimVascular's generated 0D solver input file

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/svZeroDSolver-Archived#48]
For models with coronary boundary conditions, SimVascular generates 0D solver input files with the distal pressure named as `P_v`. The 0D solver currently uses the name `Pv` instead. This mismatch results in the 0D solver not automatically running for coronary models. We need to change the 0D solver's use of `Pv` to `P_v` for compatibility.

**Comment by mrp089** [comment]
Looks good @JonathanPham! Is this change required for the current SimVascular version to run? If so, please also open a (super brief) issue in [the SimVascular repo](https://github.com/SimVascular/SimVascular) and bump up the version of the `svZeroDSolver` sub-repository (after #50 has been merged).

**Comment by JonathanPham** [comment]
@mrp089 Yes, I think this change is required for the current SimVascular version. Can you merge the changes (#50) for me? I still don't have admin privileges. 

I created the issue in the SimVascular repo to request using the updated svZeroDSolver repository. The issue can be found here: https://github.com/SimVascular/SimVascular/issues/956

**Comment by mrp089** [comment]
Merged! Sorry, didn't see this... Can you make the appropriate changes in https://github.com/SimVascular/SimVascular/issues/956? Thank you!
