### ISSUE TITLE
Create a simple two-inlet test case

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/svZeroDSolver-Archived#54]
Some people are interested in modeling networks with multiple inlets. As such, we should create a simple test case with two inlets to illustrate how a multiple-inlet model can be created.

I will tackle this.

**Comment by mrp089** [comment]
Nice to see that this already works! Sadly, our 3D->0D pipeline doesn't support this yet

**Comment by JonathanPham** [comment]
Thanks @mrp089!
