### ISSUE TITLE
Move to installation via pip

### ISSUE THREAD

**Issue by richterjakob** [SimVascular/svZeroDSolver-Archived#59]
The installation of the svZeroDSolver has been faciliated by configuring it as a pip package. The package with all its dependencies can now be installed via pip:

```bash
pip install git+https://github.com/SimVascular/svZeroDSolver.git
```
This makes it easier to implement the solver as a package in another tool (like SimVascular) without the need for configuring it as a submodule.

Morover, a command line script has been configured, so that the solver can be called via:

```bash
zerod SOLVER_INPUT_FILE 
```

**Comment by mrp089** [comment]
Awesome @richterjakob!! Can you open a brief issue in `SimVascular` to use the `pip` version (instead of the git submodule) of `svZeroDSolver`? The installation of modules via `pip` is mentioned here: https://github.com/SimVascular/SimVascular/issues/800

**Comment by richterjakob** [comment]
Thanks @mrp089 🙌 I created a respective issue in SimVascular (see [here](https://github.com/SimVascular/SimVascular/issues/965)).
